
const Strings = {
    ST01: "please input email",
    ST02: "something wrong",
    ST03: "please input password",
    ST04: "user not found",
    ST05: "wrong password",
    ST06: "password reset email sent",
    ST07: "Try Again",
    ST08: "email and password fields required",
    ST09: "please enter the valid email",
    ST10: "please enter the edu email",
    ST11: "password must be at least 8 characters",
    ST12: "profile picture required",
    ST13: "name required",
    ST14: "username required",
    ST15: "university required",
    ST16: "gender required",
    ST17: "username already exists",
    ST18: "Verify Email sent",
    ST19: "error happened while send email",
    ST20: "email already exists",
    ST21: "Email Verified! please wait...",
    ST22: "restarting...",
    ST23: "card information registered",
    ST24: "your account has been suspended",
    ST25: "input payment info",
    ST26: "please select pickup date",
    ST27: "please select pickup time",
    ST28: "please input pickup location",
    ST29: "payment access failed",
    ST30: "payment confirmed",
    ST31: "item successfully deleted",
    ST32: "you will receive your money back",
    ST33: "money was already released",
    ST34: "payment release failed",
    ST35: "money was released to seller",
    ST36: "please enter valid price",
    ST37: "passwords does not match",
    ST38: "username and name fields required",
    ST39: "profile was updated",
    ST40: "when will you be back?",
    ST41: "vacation on",
    ST42: "vacation off",
    ST43: "stripe connecting...",
    ST44: "please upload at least one picture",
    ST45: "please input title",
    ST46: "please input description",
    ST47: "please input price",
    ST48: "please input category",
    ST49: "please input brand",
    ST50: "please input gender type",
    ST51: "please input size",
    ST52: "please input color",
    ST53: "posted successfully",
    ST54: "stripe connect failed",
    ST55: "stripe connect success",
    ST56: "password updated",
    ST57: "your account has been closed successfully",
    ST58: "please input username or email",
    ST59: "your report submitted successfully",
};

export default Strings;